### ISSUE TITLE
Error message, number of features?

### ISSUE THREAD

**Issue by Sandv** [dkloz/GICF#1]
Hello Dimitrios,

Thanks for providing the code for this awesome idea. I would like to use it for medical text analysis to find important sentences in reports. I think this is the way to go, makes perfect sense!

I created embedding files (I used doc2vec for this test)
I got your tool to read the files and it does some training but then this error appears(see below).

Any idea what this could be?
I made sure that the same number of features (20 in this simplified case) is actually read. 
I attached the emb files (Replaced separator \t with X because of some encoding issue).
[emb.zip](https://github.com/dkloz/GICF/files/797414/emb.zip)

Do you have an idea what might be the problem (using python 2.7)
2.7.12 |Anaconda 2.4.1 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]

Thank you very much!
Veit

Thanks for reading our paper and using our code.
loading data... Total instances:  2718  in  200  groups Positives:  98  Negatives:  102
done  in 0.0320000648499 seconds
loading data... Total instances:  1266  in  100  groups Positives:  35  Negatives:  65
done  in 0.0149998664856 seconds
Instances:  positive:  14  Negative:  17
Optimizing for  3x10_0.5_0.04cos0.7071
-------epoch  0 -----------
#iter   ACC Train       AUC Train       ACC Test        AUC Test                |       ACC Sent     AUC Sent           PRC Sent
-------epoch  1 -----------
#iter   ACC Train       AUC Train       ACC Test        AUC Test                |       ACC Sent     AUC Sent           PRC Sent
-------epoch  2 -----------
#iter   ACC Train       AUC Train       ACC Test        AUC Test                |       ACC Sent     AUC Sent           PRC Sent
    50  51.0            ( 0.0 ) 65.0            ( 0.0 )         |       Traceback (most recent call last):
  File "cigf.py", line 21, in <module>
    gicf.train()    # this prints results
  File "H:\My Documents\MIMIC3\GICF-master\code\optimize_cost_fn.py", line 127, in train
    acc = self._print_progress(theta)
  File "H:\My Documents\MIMIC3\GICF-master\code\optimize_cost_fn.py", line 169, in _print_progress
    acc, auc = self.instance_eval.evaluate_instances(theta)
  File "H:\My Documents\MIMIC3\GICF-master\code\evaluation.py", line 103, in evaluate_instances
    y_hat = af.calculate_y(self.eval_data, self.theta)
  File "H:\My Documents\MIMIC3\GICF-master\code\array_functions.py", line 13, in calculate_y
    return sigmoid(np.dot(x, theta))
ValueError: shapes (31,20) and (19,) not aligned: 20 (dim 1) != 19 (dim 0)

(C:\Continuum\Anaconda2) H:\My Documents\MIMIC3\GICF-master\code>

**Comment by nagpaul** [comment]
So, in their paper they use some kind of instance level labelled dataset which is usually missing for general Multi Instance Learning tasks. Perhaps in that evaluation, it requires that dataset to be loaded with instance level labels. Just a guess-  I'm looking into using it myself. Do tell if you got it work.

**Comment by dkloz** [comment]
Hi, its been a year since this has been reported, so I am guessing it been resolved. 
In case it hasn't, I took a look at the emb.zip and there are some X's in there. I think the mistake is probably there, (maybe the should be tabs or spaces?)

@nagpaul in instance level evaluation you do require dataset with instance level labels, but for training and group level evaluation you do not.

Hope this helps. 
[marking as resolved]
